### ISSUE TITLE
InventoryClickEvent

### ISSUE THREAD

**Issue by ErythroCraft** [Chew/TransmuteIt#41]
**Describe the bug**

**Steps to Reproduce**
1. installing the plugin
2. starting server
3. click in in inventories
4. [latest.log](https://github.com/ChewMC/TransmuteIt/files/7269863/latest.log)

**Expected behavior**
not the bug

**Actual behavior**
the bug

**Screenshots**
nope, see the log file

**Additional context**
nope, the bug is enough

**Comment by Chew** [comment]
This _should_ be fixed on latest dev builds. Try this build: https://jenkins.chew.pw/job/ChewMC/job/TransmuteIt/65/

Been a while since I've done a release aaaa

**Comment by ErythroCraft** [comment]
wait I test it now

**Comment by ErythroCraft** [comment]
Perfect Thanks.

Can you add buttons to go back to the home GUI, too?

**Comment by Chew** [comment]
Which page? I think a few had added them.

**Comment by ErythroCraft** [comment]
Discoveries

**Comment by ErythroCraft** [comment]
![2021-10-01_22 38 14](https://user-images.githubusercontent.com/76217862/135683481-859cf3c9-d291-478c-90d5-5bbbb23b4353.png)

Now on my server set your plugin with a Cat Hat

**Comment by ErythroCraft** [comment]
I set a simple fix for the emc.json

**Comment by ErythroCraft** [comment]
Maybe you can add a /transmute reload command?

**Comment by Chew** [comment]
Tracking that in #27 😄
